---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: application-pvc
    {{- include "booklore.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
