services:
  booklore:
    env_file: "default.env"
    # Official Docker Hub image:
    image: booklore/booklore:latest
    # Or the GHCR image:
    # image: ghcr.io/booklore-app/booklore:latest
    container_name: booklore
    environment:
      - USER_ID=1000                                    # Modify this if the volume's ownership is root
      - GROUP_ID=1000                                   # Modify this if the volume's ownership is root
      - TZ=$TZ
      - DATABASE_URL=jdbc:mariadb://mariadb:3306/$DB_NAME
      - DATABASE_USERNAME=$DB_USER                      
      - DATABASE_PASSWORD=$DB_PASSWORD                      
      - BOOKLORE_PORT=$BOOKLORE_PORT                   
      - SWAGGER_ENABLED=$SWAGGER_ENABLED                              
      - FORCE_DISABLE_OIDC=$DISABLE_OIDC
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "$BOOKLORE_PORT:$BOOKLORE_PORT"
    volumes:
      - ./data:/app/data       # Application data (settings, metadata, cache, etc.). Persist this folder to retain your library state across container restarts.
      - ./books:/books         # Primary book library folder. Mount your collection here so BookLore can access and organize your books.
      - ./bookdrop:/bookdrop   # BookDrop folder. Files placed here are automatically detected and prepared for import.
    restart: unless-stopped
  mariadb:
    env_file: "default.env"
    image: lscr.io/linuxserver/mariadb:11.4.5
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD 
      - MYSQL_USER=$DB_USER                       
      - MYSQL_PASSWORD=$DB_PASSWORD
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
