---
# Default values for booklore.

app:
  image:
    tag: latest
    pull_policy: IfNotPresent
    repository: docker.io/booklore/booklore
  service:
    port: 6060
    target: 6060
    name: booklore
    type: ClusterIP
  config:
    user_id: 1000
    group_id: 1000
    timezone: Etc/UTC
    swagger_enabled: false
    force_disable_oidc: false

mariadb:
  image:
    tag: 11.4.8
    pull_policy: IfNotPresent
    repository: lscr.io/linuxserver/mariadb
  service:
    port: 3306
    target: 3306
    name: mariadb
    type: ClusterIP
  config:
    database: null
    username: null
    password: null
    root_password: null
